version: "3.8"

services:
  api:
    build:
      context: ./server
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - SERVER_PORT=3000
      - CONNECTIONSTRING=mongodb://mongo:27017/questions
    volumes:
      - .:/code
    command: npm run debug

  mongo:
    image: mongo:4.4.1
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
